import { NextRequest, NextResponse } from "next/server";
import { FieldValue, Timestamp } from "firebase-admin/firestore";
import { adminDb } from "@/lib/firebaseAdmin";
import { authorizeAdminRequest } from "@/lib/server/adminAuthorization";
import { deleteAdminImage, uploadAdminImage } from "@/lib/server/adminMedia";
import { cleanRobloxGameUrl, isProbablyRobloxGameUrl, normalizeGameContentMaturity, normalizeGameDirectoryStatus, normalizeGameGenre, type GameDirectoryStatus } from "@/lib/gameDirectory";

export const runtime = "nodejs";
const DESCRIPTION_LIMIT = 500;
function reply(body: Record<string, unknown>, status = 200) { return NextResponse.json(body,{status,headers:{"Cache-Control":"no-store"}}); }
function clean(value: FormDataEntryValue | null, maxLength: number) { return typeof value === "string" ? value.trim().slice(0,maxLength) : ""; }
function serialize(value: unknown): unknown { if (value instanceof Timestamp) return value.toDate().toISOString(); if (Array.isArray(value)) return value.map(serialize); if (value && typeof value === "object") return Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([k,v])=>[k,serialize(v)])); return value; }
function isAllowedStatus(value: unknown): value is GameDirectoryStatus { return value === "for_approval" || value === "published" || value === "pending" || value === "declined" || value === "archived"; }
async function createApprovalNotification({gameId,gameData,previousStatus,nextStatus}:{gameId:string;gameData:Record<string,unknown>;previousStatus:GameDirectoryStatus;nextStatus:GameDirectoryStatus;}) {
  const memberId = String(gameData.memberId || gameData.submittedByMemberId || "");
  if (!memberId || nextStatus !== "published" || previousStatus === "published") return false;
  const title = String(gameData.title || "Your submitted game");
  await adminDb.collection("memberNotifications").add({memberId,type:"game_approved",title:`${title} was approved`,message:"Your game is now published in the FRDA Game Directory.",href:`/games?game=${encodeURIComponent(gameId)}`,gameId,gameTitle:title,isRead:false,createdAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()});
  return true;
}
export async function GET(request:NextRequest){const authorization=await authorizeAdminRequest(request,"content_game_directory");if(!authorization.ok)return authorization.response;const snapshot=await adminDb.collection("gameDirectory").orderBy("createdAt","desc").get();return reply({ok:true,games:snapshot.docs.map(d=>({id:d.id,...(serialize(d.data()) as Record<string,unknown>)}))});}
export async function POST(request:NextRequest){
  const authorization=await authorizeAdminRequest(request,"content_game_directory"); if(!authorization.ok)return authorization.response; let uploadedPath="";
  try{
    const formData=await request.formData(); const id=clean(formData.get("id"),128); const title=clean(formData.get("title"),180); const description=clean(formData.get("description"),DESCRIPTION_LIMIT); const robloxUrl=cleanRobloxGameUrl(clean(formData.get("robloxUrl"),1000)); const creatorName=clean(formData.get("creatorName"),140); const creatorType=formData.get("creatorType")==="group"?"group":"individual"; const memberId=clean(formData.get("memberId"),80); const genre=normalizeGameGenre(clean(formData.get("genre"),80)); const contentMaturity=normalizeGameContentMaturity(clean(formData.get("contentMaturity"),80)); const isSponsored=formData.get("isSponsored")==="true"; const isHighlighted=formData.get("isHighlighted")==="true"; const requestedStatus=clean(formData.get("nextStatus"),40); const nextStatus=requestedStatus?normalizeGameDirectoryStatus(requestedStatus):undefined; const imageEntry=formData.get("thumbnail"); const thumbnail=imageEntry instanceof File && imageEntry.size>0?imageEntry:null;
    if(!title||!description||!creatorName||!robloxUrl)return reply({ok:false,error:"Complete all required game fields."},400); if(description.length>DESCRIPTION_LIMIT)return reply({ok:false,error:`Description must be ${DESCRIPTION_LIMIT} characters or less.`},400); if(!isProbablyRobloxGameUrl(robloxUrl))return reply({ok:false,error:"Please enter a valid Roblox game, share, or community link."},400);
    const reference=id?adminDb.collection("gameDirectory").doc(id):adminDb.collection("gameDirectory").doc(); const previousSnapshot=id?await reference.get():null; if(id&&!previousSnapshot?.exists)return reply({ok:false,error:"The game listing was not found."},404); const previous=previousSnapshot?.data()||{}; let thumbnailUrl=String(previous.thumbnailUrl||""); let thumbnailPath=String(previous.thumbnailPath||"");
    if(thumbnail){const uploaded=await uploadAdminImage({file:thumbnail,folder:"game-directory/thumbnails"});thumbnailUrl=uploaded.imageUrl;thumbnailPath=uploaded.imagePath;uploadedPath=uploaded.imagePath;}
    const previousStatus=normalizeGameDirectoryStatus(String(previous.status||"for_approval")); const finalStatus=nextStatus||(id?previousStatus:"for_approval");
    const payload={title,description,robloxUrl,creatorName,creatorType,memberId,genre,contentMaturity,thumbnailUrl,thumbnailPath,coverImageUrl:String(previous.coverImageUrl||""),coverImagePath:String(previous.coverImagePath||""),isSponsored,isHighlighted,isHiddenFromPublic:finalStatus!=="published",status:finalStatus,updatedAt:FieldValue.serverTimestamp(),editedByUid:authorization.staff.uid,editedByName:authorization.staff.displayName,editedByEmail:authorization.staff.emailAddress,editedAt:FieldValue.serverTimestamp(),...(id?{}:{source:"staff_added",uploadedByUid:authorization.staff.uid,uploadedByName:authorization.staff.displayName,uploadedByEmail:authorization.staff.emailAddress,uploadedAt:FieldValue.serverTimestamp(),createdAt:FieldValue.serverTimestamp()}),...(finalStatus!==previousStatus?{reviewedByUid:authorization.staff.uid,reviewedByName:authorization.staff.displayName,reviewedByEmail:authorization.staff.emailAddress,reviewedAt:FieldValue.serverTimestamp()}:{})};
    await reference.set(payload,{merge:true}); const saved=await reference.get(); const notificationCreated=await createApprovalNotification({gameId:reference.id,gameData:saved.data()||payload,previousStatus,nextStatus:finalStatus}); if(thumbnail&&previous.thumbnailPath&&previous.thumbnailPath!==thumbnailPath)await deleteAdminImage(String(previous.thumbnailPath)).catch(()=>undefined); uploadedPath=""; return reply({ok:true,id:reference.id,status:finalStatus,notificationCreated});
  }catch(error){if(uploadedPath)await deleteAdminImage(uploadedPath).catch(()=>undefined);return reply({ok:false,error:error instanceof Error?error.message:"Could not save the game listing."},500);}
}
export async function PATCH(request:NextRequest){const authorization=await authorizeAdminRequest(request,"content_game_directory");if(!authorization.ok)return authorization.response;const body=await request.json().catch(()=>null);const gameId=typeof body?.gameId==="string"?body.gameId.trim():"";const nextStatus=body?.nextStatus;if(!gameId||!isAllowedStatus(nextStatus))return reply({ok:false,error:"A valid game and review status are required."},400);const reference=adminDb.collection("gameDirectory").doc(gameId);const snapshot=await reference.get();if(!snapshot.exists)return reply({ok:false,error:"Game listing not found."},404);const data=snapshot.data()||{};const previousStatus=normalizeGameDirectoryStatus(String(data.status||""));await reference.set({status:nextStatus,isHiddenFromPublic:nextStatus!=="published",reviewedByUid:authorization.staff.uid,reviewedByName:authorization.staff.displayName||"FRDA Staff",reviewedByEmail:authorization.staff.emailAddress,reviewedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()},{merge:true});const notificationCreated=await createApprovalNotification({gameId,gameData:data,previousStatus,nextStatus});return reply({ok:true,status:nextStatus,notificationCreated});}
