import { NextRequest, NextResponse } from "next/server";
import { adminDb } from "@/lib/firebaseAdmin";
import { authorizeMemberRequest } from "@/lib/server/memberAuthorization";
import { hasDeveloperPremiumAccess } from "@/lib/server/developerPremiumLaunch";
export const runtime = "nodejs";
type RangeValue="today"|"7d"|"30d"|"all";
type Daily={profileViews:number;uniqueProfileViews:number;contactClicks:number;projectViews:number;projectLinkClicks:number;portfolioClicks:number};
const num=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)?Math.max(0,v):0;
function dayKey(d:Date){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Manila",year:"numeric",month:"2-digit",day:"2-digit"}).format(d);}
function rangeValue(v:string|null):RangeValue{return v==="today"||v==="7d"||v==="30d"||v==="all"?v:"30d";}
function rangeStart(r:RangeValue){if(r==="all")return"";const d=new Date();if(r!=="today")d.setDate(d.getDate()-(r==="7d"?6:29));return dayKey(d);}
export async function GET(request:NextRequest){try{const a=await authorizeMemberRequest(request);if(!a.ok)return a.response;const {member,memberData}=a;if(member.accountPurpose!=="developer"&&member.accountPurpose!=="both")return NextResponse.json({ok:false,error:"Developer analytics are available only to developer accounts."},{status:403});if(!hasDeveloperPremiumAccess(memberData))return NextResponse.json({ok:false,error:"Analytics are only available to eligible premium profiles."},{status:403});const range=rangeValue(request.nextUrl.searchParams.get("range"));const [aggregateSnapshot,dailySnapshot,projectsSnapshot,savesSnapshot]=await Promise.all([adminDb.collection("developerAnalytics").doc(member.uid).get(),adminDb.collection("developerAnalyticsDaily").where("developerUid","==",member.uid).get(),adminDb.collection("developerProjectAnalytics").where("developerUid","==",member.uid).get(),adminDb.collection("developerSaves").where("developerUid","==",member.uid).get()]);const aggregate=aggregateSnapshot.data()||{};const start=rangeStart(range);const series=dailySnapshot.docs.map(d=>{const x=d.data();return{dayKey:String(x.dayKey||""),profileViews:num(x.profileViews),uniqueProfileViews:num(x.uniqueProfileViews),contactClicks:num(x.contactClicks),projectViews:num(x.projectViews),projectLinkClicks:num(x.projectLinkClicks),portfolioClicks:num(x.portfolioClicks)}}).filter(x=>x.dayKey&&(!start||x.dayKey>=start)).sort((a,b)=>a.dayKey.localeCompare(b.dayKey));const empty:Daily={profileViews:0,uniqueProfileViews:0,contactClicks:0,projectViews:0,projectLinkClicks:0,portfolioClicks:0};const totals=range==="all"?{profileViews:num(aggregate.profileViews),uniqueProfileViews:num(aggregate.uniqueProfileViews),contactClicks:num(aggregate.contactClicks),projectViews:num(aggregate.projectViews),projectLinkClicks:num(aggregate.projectLinkClicks),portfolioClicks:num(aggregate.portfolioClicks)}:series.reduce<Daily>((a,x)=>({profileViews:a.profileViews+x.profileViews,uniqueProfileViews:a.uniqueProfileViews+x.uniqueProfileViews,contactClicks:a.contactClicks+x.contactClicks,projectViews:a.projectViews+x.projectViews,projectLinkClicks:a.projectLinkClicks+x.projectLinkClicks,portfolioClicks:a.portfolioClicks+x.portfolioClicks}),empty);const projects=projectsSnapshot.docs.map(d=>{const x=d.data(),detailViews=num(x.detailViews),linkClicks=num(x.linkClicks);return{projectId:String(x.projectId||""),projectTitle:String(x.projectTitle||"Untitled project"),detailViews,linkClicks,engagement:detailViews+linkClicks}}).sort((a,b)=>b.engagement-a.engagement||a.projectTitle.localeCompare(b.projectTitle)).slice(0,10);return NextResponse.json({ok:true,analyticsAccess:"pro",range,totals:{...totals,bookmarks:savesSnapshot.size},series,projects});}catch(error){console.error("Load member analytics error:",error);return NextResponse.json({ok:false,error:"Could not load your developer analytics."},{status:500});}}
